CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "BodyTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_BodyTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "FuelTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_FuelTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "GearTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_GearTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Regions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Regions" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "Password" text,
    "FirstName" text NOT NULL,
    "LastName" text,
    "PhoneNumber" text,
    "Country" text,
    "AboutYourself" text,
    "DateOfBirth" timestamp with time zone,
    "Address" text,
    "IsGoogleAuth" boolean NOT NULL,
    "IsVerified" boolean NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastModified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "VehicleBrands" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_VehicleBrands" PRIMARY KEY ("Id")
);

CREATE TABLE "VehicleConditions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_VehicleConditions" PRIMARY KEY ("Id")
);

CREATE TABLE "VehicleTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_VehicleTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Cities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RegionId" integer NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cities_Regions_RegionId" FOREIGN KEY ("RegionId") REFERENCES "Regions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmailVerificationCodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NOT NULL,
    "ExpirationTime" timestamp with time zone NOT NULL,
    "Type" integer NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_EmailVerificationCodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmailVerificationCodes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserAvatars" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Url" text NOT NULL,
    "Hash" text,
    "PublicId" text,
    "IsExternal" boolean NOT NULL,
    CONSTRAINT "PK_UserAvatars" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserAvatars_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "VehicleModels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleTypeId" integer NOT NULL,
    "BrandId" integer NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_VehicleModels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VehicleModels_VehicleBrands_BrandId" FOREIGN KEY ("BrandId") REFERENCES "VehicleBrands" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleModels_VehicleTypes_VehicleTypeId" FOREIGN KEY ("VehicleTypeId") REFERENCES "VehicleTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "VehicleListings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ModelId" integer,
    "GearTypeId" integer,
    "BodyTypeId" integer,
    "ConditionId" integer,
    "FuelTypeId" integer,
    "ColorHex" character varying(7),
    "CityId" integer,
    "Year" integer,
    "Description" character varying(2000),
    "Mileage" integer,
    "HasAccident" boolean,
    "Price" numeric(18,2),
    "Number" text,
    "IsPublished" boolean NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastModified" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehicleListings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VehicleListings_BodyTypes_BodyTypeId" FOREIGN KEY ("BodyTypeId") REFERENCES "BodyTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleListings_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleListings_FuelTypes_FuelTypeId" FOREIGN KEY ("FuelTypeId") REFERENCES "FuelTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleListings_GearTypes_GearTypeId" FOREIGN KEY ("GearTypeId") REFERENCES "GearTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleListings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VehicleListings_VehicleConditions_ConditionId" FOREIGN KEY ("ConditionId") REFERENCES "VehicleConditions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleListings_VehicleModels_ModelId" FOREIGN KEY ("ModelId") REFERENCES "VehicleModels" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "VehicleModelBodyTypes" (
    "VehicleModelId" integer NOT NULL,
    "BodyTypeId" integer NOT NULL,
    CONSTRAINT "PK_VehicleModelBodyTypes" PRIMARY KEY ("VehicleModelId", "BodyTypeId"),
    CONSTRAINT "FK_VehicleModelBodyTypes_BodyTypes_BodyTypeId" FOREIGN KEY ("BodyTypeId") REFERENCES "BodyTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VehicleModelBodyTypes_VehicleModels_VehicleModelId" FOREIGN KEY ("VehicleModelId") REFERENCES "VehicleModels" ("Id") ON DELETE CASCADE
);

CREATE TABLE "VehiclePhotos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleListingId" integer NOT NULL,
    "PhotoUrl" text NOT NULL,
    "PublicId" text NOT NULL,
    "Hash" text NOT NULL,
    CONSTRAINT "PK_VehiclePhotos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VehiclePhotos_VehicleListings_VehicleListingId" FOREIGN KEY ("VehicleListingId") REFERENCES "VehicleListings" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_BodyTypes_Name" ON "BodyTypes" ("Name");

CREATE UNIQUE INDEX "IX_Cities_RegionId_Name" ON "Cities" ("RegionId", "Name");

CREATE INDEX "IX_EmailVerificationCodes_UserId" ON "EmailVerificationCodes" ("UserId");

CREATE UNIQUE INDEX "IX_FuelTypes_Name" ON "FuelTypes" ("Name");

CREATE UNIQUE INDEX "IX_GearTypes_Name" ON "GearTypes" ("Name");

CREATE UNIQUE INDEX "IX_Regions_Name" ON "Regions" ("Name");

CREATE UNIQUE INDEX "IX_UserAvatars_UserId" ON "UserAvatars" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_VehicleBrands_Name" ON "VehicleBrands" ("Name");

CREATE UNIQUE INDEX "IX_VehicleConditions_Name" ON "VehicleConditions" ("Name");

CREATE INDEX "IX_VehicleListings_BodyTypeId" ON "VehicleListings" ("BodyTypeId");

CREATE INDEX "IX_VehicleListings_CityId" ON "VehicleListings" ("CityId");

CREATE INDEX "IX_VehicleListings_ConditionId" ON "VehicleListings" ("ConditionId");

CREATE INDEX "IX_VehicleListings_FuelTypeId" ON "VehicleListings" ("FuelTypeId");

CREATE INDEX "IX_VehicleListings_GearTypeId" ON "VehicleListings" ("GearTypeId");

CREATE INDEX "IX_VehicleListings_ModelId" ON "VehicleListings" ("ModelId");

CREATE INDEX "IX_VehicleListings_UserId" ON "VehicleListings" ("UserId");

CREATE INDEX "IX_VehicleModelBodyTypes_BodyTypeId" ON "VehicleModelBodyTypes" ("BodyTypeId");

CREATE INDEX "IX_VehicleModels_BrandId" ON "VehicleModels" ("BrandId");

CREATE INDEX "IX_VehicleModels_VehicleTypeId" ON "VehicleModels" ("VehicleTypeId");

CREATE INDEX "IX_VehiclePhotos_VehicleListingId" ON "VehiclePhotos" ("VehicleListingId");

CREATE UNIQUE INDEX "IX_VehicleTypes_Name" ON "VehicleTypes" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251118131527_InitDatabase', '9.0.10');

ALTER TABLE "VehiclePhotos" ALTER COLUMN "VehicleListingId" DROP NOT NULL;

ALTER TABLE "VehiclePhotos" ADD "SortOrder" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251120161827_PhotoSortOrder', '9.0.10');

ALTER TABLE "EmailVerificationCodes" DROP CONSTRAINT "FK_EmailVerificationCodes_Users_UserId";

ALTER TABLE "UserAvatars" DROP CONSTRAINT "FK_UserAvatars_Users_UserId";

ALTER TABLE "VehicleListings" DROP CONSTRAINT "FK_VehicleListings_Users_UserId";

ALTER TABLE "Users" DROP CONSTRAINT "PK_Users";

ALTER TABLE "Users" RENAME TO "AspNetUsers";

ALTER TABLE "AspNetUsers" RENAME COLUMN "Password" TO "SecurityStamp";

ALTER TABLE "AspNetUsers" RENAME COLUMN "IsVerified" TO "TwoFactorEnabled";

ALTER INDEX "IX_Users_Email" RENAME TO "IX_AspNetUsers_Email";

ALTER TABLE "VehicleListings" ADD "IsVerified" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "VehicleListings" ADD "Vin" text;

ALTER TABLE "AspNetUsers" ALTER COLUMN "Email" TYPE character varying(256);
ALTER TABLE "AspNetUsers" ALTER COLUMN "Email" DROP NOT NULL;

ALTER TABLE "AspNetUsers" ADD "AccessFailedCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "AspNetUsers" ADD "ConcurrencyStamp" text;

ALTER TABLE "AspNetUsers" ADD "EmailConfirmed" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "LockoutEnabled" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "LockoutEnd" timestamp with time zone;

ALTER TABLE "AspNetUsers" ADD "NormalizedEmail" character varying(256);

ALTER TABLE "AspNetUsers" ADD "NormalizedUserName" character varying(256);

ALTER TABLE "AspNetUsers" ADD "PasswordHash" text;

ALTER TABLE "AspNetUsers" ADD "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "UserName" character varying(256);

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");

CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

ALTER TABLE "EmailVerificationCodes" ADD CONSTRAINT "FK_EmailVerificationCodes_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "UserAvatars" ADD CONSTRAINT "FK_UserAvatars_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "VehicleListings" ADD CONSTRAINT "FK_VehicleListings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251211132817_NewFieldsInListing', '9.0.10');

COMMIT;

