using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class CreateFavouriteFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "VehicleListings"
                ADD COLUMN IF NOT EXISTS "Latitude" numeric NOT NULL DEFAULT 0.0;
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "VehicleListings"
                ADD COLUMN IF NOT EXISTS "Longitude" numeric NOT NULL DEFAULT 0.0;
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "FavouriteVehicles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" integer NOT NULL,
                    "VehicleListingId" integer NOT NULL,
                    CONSTRAINT "PK_FavouriteVehicles" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_FavouriteVehicles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_FavouriteVehicles_VehicleListings_VehicleListingId" FOREIGN KEY ("VehicleListingId") REFERENCES "VehicleListings" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_FavouriteVehicles_UserId"
                ON "FavouriteVehicles" ("UserId");
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_FavouriteVehicles_VehicleListingId"
                ON "FavouriteVehicles" ("VehicleListingId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FavouriteVehicles");

            migrationBuilder.DropColumn(
                name: "Latitude",
                table: "VehicleListings");

            migrationBuilder.DropColumn(
                name: "Longitude",
                table: "VehicleListings");
        }
    }
}
